# zmodload zsh/zprof # uncomment for profiling
export ZSH=${HOME}/.oh-my-zsh
source "${HOME}/.zsh/user.sh"
source "${HOME}/.zsh/plugins.sh"
source "${HOME}/.zsh/options.sh"
source "${ZSH}/oh-my-zsh.sh"
source "${HOME}/.zsh/exports.sh"
source "${HOME}/.zsh/aliases.sh"
source "${HOME}/.zsh/functions.sh"
source "${HOME}/.zsh/os.sh"
source "${HOME}/.zsh/macos.sh"
source "${HOME}/.zsh/linux.sh"
source "${HOME}/.zsh/nextcloud.sh"
source "${HOME}/.zsh/archive.sh"
source "${HOME}/.zsh/python.sh"
source "${HOME}/.zsh/rust.sh"
source "${HOME}/.zsh/go.sh"
source "${HOME}/.zsh/node.sh"
source "${HOME}/.zsh/sqlite.sh"
source "${HOME}/.zsh/vscode.sh"
source "${HOME}/.zsh/sublime.sh"
source "${HOME}/.zsh/ruby.sh"
compinit -d "${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"
# zprof # uncomment for profiling
