---
- name: Download the Chrome .deb
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/chrome.deb
    mode: "0644"
  register: linux_chrome_deb

- name: Install Chrome
  ansible.builtin.apt:
    deb: "{{ linux_chrome_deb.dest }}"
    state: present
  become: true
