---
- name: Download the NodeSource setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_{{ linux_node_major }}.x
    dest: /tmp/nodesource_setup.sh
    mode: "0755"
  register: linux_nodesource_script

- name: Run the NodeSource setup script
  ansible.builtin.shell: /tmp/nodesource_setup.sh
  become: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
  become: true

- name: Remove the NodeSource setup script
  ansible.builtin.file:
    path: /tmp/nodesource_setup.sh
    state: absent
