---
- name: Install gnupg2
  ansible.builtin.apt:
    name: gnupg2
    state: present
  become: true

- name: Download the 1Password .deb
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    dest: /tmp/1password.deb
    mode: "0644"
  register: linux_1password_deb

- name: Install 1Password
  ansible.builtin.apt:
    deb: "{{ linux_1password_deb.dest }}"
    state: present
  become: true
