---
- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: Check for tpm
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.tmux/plugins/tpm"
  register: linux_tpm

- name: Clone tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux/plugins/tpm"
    update: false
  when: not linux_tpm.stat.exists
